### ISSUE TITLE
Publish 0.8.2 to Maven Central

### ISSUE THREAD

**Issue by mkobit** [ottogroup/flink-spector#74]
It looks like the tag was pushed up (https://github.com/ottogroup/flink-spector/releases/tag/r0.8.2_2.11) but the latest libraries on Maven Central now are for `0.8.1` (https://mvnrepository.com/artifact/io.flinkspector/flinkspector-core).

**Comment by lofifnc** [comment]
I made a mistake with the version numbers. i have fixed this by now.

**Comment by mkobit** [comment]
Sorry to poke at this again, but I'm still not seeing them at https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.flinkspector%22%20AND%20a%3A%22flinkspector-core_2.11%22 (or the other artifacts).

**Comment by lofifnc** [comment]
Your right I shouldn't do so many things at once.
I forgot to check if the sync with maven central actually worked.

**Comment by lofifnc** [comment]
http://repo1.maven.org/maven2/io/flinkspector/flinkspector-core_2.11/

now we're good!

**Comment by mkobit** [comment]
Ha! Sorry for the trouble!

Thanks for the quick turnaround!
